#!/usr/bin/env python3
"""Checkpoint material 1 to 4, assembled from results/*.json and the tables under data/ (no hand-typed numbers).

checkpoint_summary.py  ->  results/checkpoints.md
"""

import json
import random
import subprocess
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
R, D = ROOT / "results", ROOT / "data"


def load(name: str) -> dict:
    p = R / name
    return json.loads(p.read_text()) if p.exists() else {}


def du(path: Path) -> str:
    out = subprocess.run(["du", "-sh", str(path)], capture_output=True, text=True).stdout.split()
    return out[0] if out else "?"


def table(rows: list[tuple], header: tuple) -> str:
    return "\n".join(
        [
            "| " + " | ".join(header) + " |",
            "|" + "---|" * len(header),
            *("| " + " | ".join(str(c) for c in r) + " |" for r in rows),
        ]
    )


def main() -> None:
    acq, reg, ext, rules, pool, dev = (
        load(n)
        for n in (
            "acquisition_stats.json",
            "registry_stats.json",
            "extract_stats.json",
            "rules_stats.json",
            "pool_stats.json",
            "deviations_stats.json",
        )
    )
    out = ["# Checkpoint material (generated by scripts/checkpoint_summary.py from results/*.json)", ""]
    rng = random.Random(7)

    out += ["## Checkpoint 1: acquisition", ""]
    out.append(
        f"- Pool: {pool.get('unique_solicitations', '?')} unique solicitations found in {pool.get('search_days', '?')} sampled weekdays; {pool.get('selected', '?')} selected (200 per month, 2024-10 to 2026-09); max department share {pool.get('max_department_share', 0):.1%}."
    )
    out.append(
        f"- Downloaded so far: {acq.get('notices_done', '?')} of {acq.get('notices_selected', '?')} notices; files by status {acq.get('files_by_status')}; not stored by reason {acq.get('files_not_stored_by_reason')}."
    )
    out.append(
        f"- Unique documents {acq.get('documents_unique_sha256')}, {acq.get('bytes_unique', 0) / 1e9:.2f} GB; by type {acq.get('by_file_type')}; API calls {acq.get('api_calls')}."
    )
    out.append(f"- Disk now: data/raw/files {du(D / 'raw' / 'files')}, whole data/ {du(D)}.")
    docs_p, notices_p = D / "interim" / "documents.parquet", D / "interim" / "notices.parquet"
    if docs_p.exists() and notices_p.exists():
        docs, notices = (
            pd.read_parquet(docs_p).drop_duplicates("doc_id"),
            pd.read_parquet(notices_p).set_index("notice_id"),
        )
        sample = docs.iloc[sorted(rng.sample(range(len(docs)), min(10, len(docs))))]
        rows = [
            (
                str(notices.loc[r.notice_id, "title"])[:60],
                str(r.agency).split(".")[0][:34],
                r.filename[:36],
                f"{r.size_bytes / 1e6:.2f} MB",
                r.posted_date[:10],
            )
            for r in sample.itertuples()
        ]
        out += ["", "10 random documents:", "", table(rows, ("notice title", "agency", "file", "size", "posted"))]

    out += ["", "## Checkpoint 2: registry", ""]
    out.append(
        f"- eCFR Title 48 as of {reg.get('ecfr_as_of')}; {reg.get('sections')} sections; status {reg.get('by_status')}; earliest snapshot with text {reg.get('earliest_snapshot_with_text')}."
    )
    out.append(
        f"- Kind among active sections: {reg.get('kind_active')} (unknown = no explicit prescription sentence or a conflict)."
    )
    out += ["", table(sorted(reg.get("by_regulation", {}).items(), key=lambda kv: -kv[1]), ("regulation", "sections"))]
    reg_p = D / "processed" / "registry.parquet"
    if reg_p.exists():
        df = pd.read_parquet(reg_p)
        act = df[df["status"] == "active"].reset_index(drop=True)
        rows = [
            (
                r.number,
                r.regulation,
                r.kind,
                r.current_date,
                r.title[:46],
                f"https://www.ecfr.gov/current/title-48/section-{r.number}",
            )
            for r in act.iloc[sorted(rng.sample(range(len(act)), 10))].itertuples()
        ]
        out += ["", "10 sampled active rows:", "", table(rows, ("number", "reg", "kind", "date", "title", "eCFR"))]
    out += [
        "",
        f"- RFO deviations: model deviation {dev.get('model_deviation')}; RFO Part 52 sections {dev.get('rfo_status')}; agency PDFs parsed {dev.get('agency_pdfs_parsed')} of {dev.get('agency_pdfs')}. {dev.get('not_located', '')}",
    ]

    out += ["", "## Checkpoint 3: extraction", ""]
    out.append(
        f"- {ext.get('extracted')} documents extracted, {ext.get('pages')} pages, {ext.get('scanned_documents')} scanned, errors {ext.get('errors')}."
    )
    out.append(
        f"- Documents with any box signal {ext.get('documents_with_any_box')}; with form widgets {ext.get('documents_with_widgets')}."
    )
    out += [
        "",
        table(list(ext.get("box_counts_by_source_and_state", {}).items()), ("source:state", "boxes")),
        "",
        f"- Private-use code points still unverified or ignored: {ext.get('unverified_private_use_codepoints')}.",
        f"- Banner markings in {ext.get('documents_with_any_banner_marking')} documents; keyword mentions {ext.get('documents_mentioning_a_marking_keyword')}.",
        "- HTML: data/reports/extract_report.html.",
    ]

    out += ["", "## Checkpoint 4: candidates and baselines", ""]
    out.append(
        f"- {rules.get('documents')} documents, {rules.get('candidates')} candidates in {rules.get('documents_with_candidates')} documents; B1 roles {rules.get('b1_roles')}."
    )
    out.append(
        f"- Binding entries (distinct number per document, summed): B0 status quo {rules.get('b0_ledger_total')}, B1 rules {rules.get('b1_ledger_total')}. **Neither is validated against gold yet**; the ratio is only a preliminary signal."
    )
    out.append("- HTML: data/reports/rules_report.html.")
    (R / "checkpoints.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    print("\n".join(out))


if __name__ == "__main__":
    sys.exit(main())
